### PR TITLE
Add Ruby 2.4 support, various fixes

### PR DESCRIPTION
**Pull request by busterb**
This includes some fixes I found in @egypt's old fork, pluse updates to work with Ruby 2.4's Integer unification.

### CODE REVIEW

**Comment by michalfita** [comment]
Suggest to review with `?w=1` added to the URL, otherwise plenty of whitespace changes blurs the picture.

**Comment by busterb** [comment]
Would you guys like me to elide the whitespace cleanup? Would that help move it forward? Sorry, the hordes are gathering at the gate for Ruby 2.4 support in Metasploit :)

**Comment by vjoel** [comment]
Hey, who wants to be a collaborator? Or transfer the project to an org? Metasploit?

**Comment by busterb** [comment]
I don't mind taking this over if it helps.

**Pull request merged**
